apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
      description: Repository URL to clone
    - name: revision
      type: string
      default: main
    - name: deleteExisting
      type: string
      default: "true"
  workspaces:
    - name: output
      description: The workspace where code will be cloned
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        set -e
        if [ "$(params.deleteExisting)" = "true" ]; then
          rm -rf $(workspaces.output.path)/*
        fi
        git clone --branch $(params.revision) $(params.url) $(workspaces.output.path)
