apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: github-demo-pipeline-v1
spec:
  params:
    - name: repo-url
      type: string
  workspaces:
    - name: shared-data
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-v1
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"

    - name: say-hello
      runAfter:
        - clone-repo
      taskRef:
        name: hello-task-v1        # <-- doesn't use a workspace now
      # (removed the workspace mapping)

    - name: say-goodbye
      runAfter:
        - say-hello
      taskRef:
        name: goodbye-task-v1
