apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello-task-v1
spec:
  steps:
    - name: print
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        #!/bin/sh
        echo "Hello OpenShift — this is a standalone Task!"
